In [1]:
import pandas as pd

In [16]:
df = pd.read_csv(r"data\US_weather\US_weather_all.csv")

In [17]:
df.head()

,Unnamed: 0,STATION,NAME,LATITUDE,LONGITUDE,ELEVATION,DATE,AWND,EVAP,FMTM,PGTM,PRCP,SN52,SN53,SN55,SNOW,SNWD,SX02,SX52,SX53,SX55,TAVG,TMAX,TMIN,TOBS,WDF1,WDF2,WDF5,WDMV,WSF1,WSF2,WSF5,WSFG
0,0,USW00014607,"CARIBOU WEATHER FORECAST OFFICE, ME US",46.8705,-68.0173,190.2,1991-12-31,2.8,NaN,1050.0,NaN,0.0,NaN,NaN,NaN,0.0,127.0,-1.1,NaN,NaN,NaN,NaN,-3.3,-22.2,NaN,190.0,NaN,NaN,NaN,4.0,NaN,NaN,NaN
1,1,USW00014607,"CARIBOU WEATHER FORECAST OFFICE, ME US",46.8705,-68.0173,190.2,1992-01-01,2.0,NaN,1250.0,NaN,0.0,NaN,NaN,NaN,0.0,127.0,-1.7,NaN,NaN,NaN,NaN,-5.6,-16.1,NaN,310.0,NaN,NaN,NaN,4.0,NaN,NaN,NaN
2,2,USW00014607,"CARIBOU WEATHER FORECAST OFFICE, ME US",46.8705,-68.0173,190.2,1992-01-02,1.8,NaN,1651.0,NaN,0.0,NaN,NaN,NaN,0.0,127.0,-1.7,NaN,NaN,NaN,NaN,-3.3,-20.6,NaN,170.0,NaN,NaN,NaN,3.6,NaN,NaN,NaN
3,3,USW00014607,"CARIBOU WEATHER FORECAST OFFICE, ME US",46.8705,-68.0173,190.2,1992-01-03,1.4,NaN,1850.0,NaN,0.0,NaN,NaN,NaN,0.0,127.0,-2.2,NaN,NaN,NaN,NaN,-5.0,-17.2,NaN,50.0,NaN,NaN,NaN,2.7,NaN,NaN,NaN
4,4,USW00014607,"CARIBOU WEATHER FORECAST OFFICE, ME US",46.8705,-68.0173,190.2,1992-01-04,0.9,NaN,1451.0,NaN,0.0,NaN,NaN,NaN,0.0,127.0,-2.2,NaN,NaN,NaN,NaN,-1.7,-15.0,NaN,210.0,NaN,NaN,NaN,2.7,NaN,NaN,NaN

In [22]:
s = df['STATION'].value_counts()

In [25]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

In [17]:
df.drop('Unnamed: 0', axis=1, inplace=True)

In [ ]:
df.loc[:, ~df.columns.isin(['STATION', 'LATITUDE', 'LONGITUDE', 'DATE', 'ELEVATION'])].set_index('NAME').isna().groupby(level=0).mean().round(4).mul(100)

# wild fires data

In [1]:
import sqlite3
import pandas as pd

In [11]:
con = sqlite3.connect("data\wildfires\FPA_FOD_20170508.sqlite")

In [12]:
df = pd.read_sql_query("SELECT * FROM 'Fires'", con)
df.columns

Index(['OBJECTID', 'FOD_ID', 'FPA_ID', 'SOURCE_SYSTEM_TYPE', 'SOURCE_SYSTEM',
       'NWCG_REPORTING_AGENCY', 'NWCG_REPORTING_UNIT_ID',
       'NWCG_REPORTING_UNIT_NAME', 'SOURCE_REPORTING_UNIT',
       'SOURCE_REPORTING_UNIT_NAME', 'LOCAL_FIRE_REPORT_ID',
       'LOCAL_INCIDENT_ID', 'FIRE_CODE', 'FIRE_NAME',
       'ICS_209_INCIDENT_NUMBER', 'ICS_209_NAME', 'MTBS_ID', 'MTBS_FIRE_NAME',
       'COMPLEX_NAME', 'FIRE_YEAR', 'DISCOVERY_DATE', 'DISCOVERY_DOY',
       'DISCOVERY_TIME', 'STAT_CAUSE_CODE', 'STAT_CAUSE_DESCR', 'CONT_DATE',
       'CONT_DOY', 'CONT_TIME', 'FIRE_SIZE', 'FIRE_SIZE_CLASS', 'LATITUDE',
       'LONGITUDE', 'OWNER_CODE', 'OWNER_DESCR', 'STATE', 'COUNTY',
       'FIPS_CODE', 'FIPS_NAME', 'Shape'],
      dtype='object')

In [12]:
df.head()

,OBJECTID,FOD_ID,FPA_ID,SOURCE_SYSTEM_TYPE,SOURCE_SYSTEM,NWCG_REPORTING_AGENCY,NWCG_REPORTING_UNIT_ID,NWCG_REPORTING_UNIT_NAME,SOURCE_REPORTING_UNIT,SOURCE_REPORTING_UNIT_NAME,LOCAL_FIRE_REPORT_ID,LOCAL_INCIDENT_ID,FIRE_CODE,FIRE_NAME,ICS_209_INCIDENT_NUMBER,ICS_209_NAME,MTBS_ID,MTBS_FIRE_NAME,COMPLEX_NAME,FIRE_YEAR,DISCOVERY_DATE,DISCOVERY_DOY,DISCOVERY_TIME,STAT_CAUSE_CODE,STAT_CAUSE_DESCR,CONT_DATE,CONT_DOY,CONT_TIME,FIRE_SIZE,FIRE_SIZE_CLASS,LATITUDE,LONGITUDE,OWNER_CODE,OWNER_DESCR,STATE,COUNTY,FIPS_CODE,FIPS_NAME
0,1,1,FS-1418826,FED,FS-FIRESTAT,FS,USCAPNF,Plumas National Forest,0511,Plumas National Forest,1,PNF-47,BJ8K,FOUNTAIN,None,None,None,None,None,2005,2453403.5,33,1300,9.0,Miscellaneous,2453403.5,33.0,1730,0.10,A,40.036944,-121.005833,5.0,USFS,CA,63,063,Plumas
1,2,2,FS-1418827,FED,FS-FIRESTAT,FS,USCAENF,Eldorado National Forest,0503,Eldorado National Forest,13,13,AAC0,PIGEON,None,None,None,None,None,2004,2453137.5,133,0845,1.0,Lightning,2453137.5,133.0,1530,0.25,A,38.933056,-120.404444,5.0,USFS,CA,61,061,Placer
2,3,3,FS-1418835,FED,FS-FIRESTAT,FS,USCAENF,Eldorado National Forest,0503,Eldorado National Forest,27,021,A32W,SLACK,None,None,None,None,None,2004,2453156.5,152,1921,5.0,Debris Burning,2453156.5,152.0,2024,0.10,A,38.984167,-120.735556,13.0,STATE OR PRIVATE,CA,17,017,El Dorado
3,4,4,FS-1418845,FED,FS-FIRESTAT,FS,USCAENF,Eldorado National Forest,0503,Eldorado National Forest,43,6,None,DEER,None,None,None,None,None,2004,2453184.5,180,1600,1.0,Lightning,2453189.5,185.0,1400,0.10,A,38.559167,-119.913333,5.0,USFS,CA,3,003,Alpine
4,5,5,FS-1418847,FED,FS-FIRESTAT,FS,USCAENF,Eldorado National Forest,0503,Eldorado National Forest,44,7,None,STEVENOT,None,None,None,None,None,2004,2453184.5,180,1600,1.0,Lightning,2453189.5,185.0,1200,0.10,A,38.559167,-119.933056,5.0,USFS,CA,3,003,Alpine

In [5]:
df1000 = df.iloc[:1000,:]

In [15]:
df.to_parquet('data/wildfires.parquet', compression=None)

In [13]:
len(df)

1880465

In [2]:
df = pd.read_parquet("data\wildfires.parquet")
pd.set_option("display.max_columns", None)
df.head(5)

,OBJECTID,FOD_ID,FPA_ID,SOURCE_SYSTEM_TYPE,SOURCE_SYSTEM,NWCG_REPORTING_AGENCY,NWCG_REPORTING_UNIT_ID,NWCG_REPORTING_UNIT_NAME,SOURCE_REPORTING_UNIT,SOURCE_REPORTING_UNIT_NAME,LOCAL_FIRE_REPORT_ID,LOCAL_INCIDENT_ID,FIRE_CODE,FIRE_NAME,ICS_209_INCIDENT_NUMBER,ICS_209_NAME,MTBS_ID,MTBS_FIRE_NAME,COMPLEX_NAME,FIRE_YEAR,DISCOVERY_DATE,DISCOVERY_DOY,DISCOVERY_TIME,STAT_CAUSE_CODE,STAT_CAUSE_DESCR,CONT_DATE,CONT_DOY,CONT_TIME,FIRE_SIZE,FIRE_SIZE_CLASS,LATITUDE,LONGITUDE,OWNER_CODE,OWNER_DESCR,STATE,COUNTY,FIPS_CODE,FIPS_NAME
0,1,1,FS-1418826,FED,FS-FIRESTAT,FS,USCAPNF,Plumas National Forest,0511,Plumas National Forest,1,PNF-47,BJ8K,FOUNTAIN,None,None,None,None,None,2005,2453403.5,33,1300,9.0,Miscellaneous,2453403.5,33.0,1730,0.10,A,40.036944,-121.005833,5.0,USFS,CA,63,063,Plumas
1,2,2,FS-1418827,FED,FS-FIRESTAT,FS,USCAENF,Eldorado National Forest,0503,Eldorado National Forest,13,13,AAC0,PIGEON,None,None,None,None,None,2004,2453137.5,133,0845,1.0,Lightning,2453137.5,133.0,1530,0.25,A,38.933056,-120.404444,5.0,USFS,CA,61,061,Placer
2,3,3,FS-1418835,FED,FS-FIRESTAT,FS,USCAENF,Eldorado National Forest,0503,Eldorado National Forest,27,021,A32W,SLACK,None,None,None,None,None,2004,2453156.5,152,1921,5.0,Debris Burning,2453156.5,152.0,2024,0.10,A,38.984167,-120.735556,13.0,STATE OR PRIVATE,CA,17,017,El Dorado
3,4,4,FS-1418845,FED,FS-FIRESTAT,FS,USCAENF,Eldorado National Forest,0503,Eldorado National Forest,43,6,None,DEER,None,None,None,None,None,2004,2453184.5,180,1600,1.0,Lightning,2453189.5,185.0,1400,0.10,A,38.559167,-119.913333,5.0,USFS,CA,3,003,Alpine
4,5,5,FS-1418847,FED,FS-FIRESTAT,FS,USCAENF,Eldorado National Forest,0503,Eldorado National Forest,44,7,None,STEVENOT,None,None,None,None,None,2004,2453184.5,180,1600,1.0,Lightning,2453189.5,185.0,1200,0.10,A,38.559167,-119.933056,5.0,USFS,CA,3,003,Alpine

In [30]:
df.columns

Index(['OBJECTID', 'FOD_ID', 'FPA_ID', 'SOURCE_SYSTEM_TYPE', 'SOURCE_SYSTEM',
       'NWCG_REPORTING_AGENCY', 'NWCG_REPORTING_UNIT_ID',
       'NWCG_REPORTING_UNIT_NAME', 'SOURCE_REPORTING_UNIT',
       'SOURCE_REPORTING_UNIT_NAME', 'LOCAL_FIRE_REPORT_ID',
       'LOCAL_INCIDENT_ID', 'FIRE_CODE', 'FIRE_NAME',
       'ICS_209_INCIDENT_NUMBER', 'ICS_209_NAME', 'MTBS_ID', 'MTBS_FIRE_NAME',
       'COMPLEX_NAME', 'FIRE_YEAR', 'DISCOVERY_DATE', 'DISCOVERY_DOY',
       'DISCOVERY_TIME', 'STAT_CAUSE_CODE', 'STAT_CAUSE_DESCR', 'CONT_DATE',
       'CONT_DOY', 'CONT_TIME', 'FIRE_SIZE', 'FIRE_SIZE_CLASS', 'LATITUDE',
       'LONGITUDE', 'OWNER_CODE', 'OWNER_DESCR', 'STATE', 'COUNTY',
       'FIPS_CODE', 'FIPS_NAME'],
      dtype='object')

In [32]:
df['LOCAL_FIRE_REPORT_ID'][~df['LOCAL_FIRE_REPORT_ID'].isna()]

0               1
1              13
2              27
3              43
4              44
            ...
1880460    591814
1880461    569419
1880462    574245
1880463    570462
1880464    535436
Name: LOCAL_FIRE_REPORT_ID, Length: 421179, dtype: object

In [ ]:
df = pd.read_sql_query("SELECT FIRE_YEAR,STAT_CAUSE_DESCR,LATITUDE,LONGITUDE,STATE,DISCOVERY_DATE,FIRE_SIZE FROM 'Fires'", con)
print(df.head())

In [ ]:
df.groupby(df.columns.tolist(),as_index=False).size()

In [1]:
import psycopg2

In [2]:
conn = psycopg2.connect("host=localhost dbname=capstone user=postgres")
cur = conn.cursor()

SyntaxError: invalid syntax (2346159556.py, line 1)

# copy from files

In [11]:
conn_string = "postgresql://postgres@localhost:5432/capstone"

In [5]:
%load_ext sql

In [12]:
%sql $conn_string

In [42]:
query = ("""
    COPY staging_weather
    FROM 'C://Users//Public//US_weather_all.csv'
    DELIMITER ','
    CSV HEADER;
    """)
cur.execute(query)
conn.commit()

In [35]:
cur.execute("rollback;")